name: Publish on push tags on master

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - name: Test and publish
        run: ./build.sh Publish --feed https://api.nuget.org/v3/index.json --apikey ${{ secrets.NUGETAPIKEY }} 
