name: Regular master build and publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Setup GitVersions 
      uses: actions/setup-gitversion@v1.0.0
      with:
        gitversion-version: 5.1.1
    
    - name: Run nuke for publishing
      run: ./build.sh Publish --feed https://www.myget.org/F/oxffaa/api/v3/index.json --apikey ${{ secrets.MYGETAPIKEY }}
    
    - name: Upload code coverage
      uses: codecov/codecov-action@v1.0.11
      with:
        directory: ./artifacts 
